{% set name = "kubeseal" %}
{% set version = "0.27.1" %}

package:
  name: kubeseal
  version: {{ version }}

source:
  - url: https://github.com/bitnami-labs/sealed-secrets/archive/refs/tags/v{{ version }}.tar.gz
    sha256: 36296b854d66a21c14bc6b80037b4cac54b2a5e2965c70fb826e0558b57cb0e1
    folder: src

build:
  number: 1

requirements:
  build:
    - {{ compiler('go-nocgo') }}
    - go-licenses

test:
  commands:
    - kubeseal --help
    - kubeseal --version

about:
  home: https://sealed-secrets.netlify.app/
  license: Apache-2.0
  license_family: Apache
  license_file:
    - src/LICENSE
    - library_licenses/
  summary: Kubernetes controller and tool for one-way encrypted Secrets
  dev_url: https://github.com/bitnami-labs/sealed-secrets

extra:
  recipe-maintainers:
    - '0xbe7a'
