{% set name = "kubeseal" %}
{% set version = "0.38.4" %}

package:
  name: kubeseal
  version: {{ version }}

source:
  - url: https://github.com/bitnami-labs/sealed-secrets/archive/refs/tags/v{{ version }}.tar.gz
    sha256: 7076a3278ac29e5f3f8ac6676414e4c24f01303c1405b99a1caebe88f5977d7e
    folder: src

build:
  number: 0
  skip: true  # [win]
  script:
    - cd src
    - go install -v ./cmd/kubeseal
    - go-licenses save ./cmd/kubeseal --save_path ../library_licenses

requirements:
  build:
    - {{ compiler('go-nocgo') }}
    - go-licenses

test:
  commands:
    - kubeseal --help
    - kubeseal --version

about:
  home: https://sealed-secrets.netlify.app/
  license: Apache-2.0
  license_family: Apache
  license_file:
    - src/LICENSE
    - library_licenses/
  summary: Kubernetes controller and tool for one-way encrypted Secrets
  dev_url: https://github.com/bitnami-labs/sealed-secrets

extra:
  recipe-maintainers:
    - '0xbe7a'
